name: Java CI with Maven

on:
  push:
    branches-ignore: []
  pull_request:
    branches-ignore: []

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean test jacoco:report

      - name: Upload JaCoCo Test Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco_reports
          path: target/site/jacoco